# Generated by Django 3.0.2 on 2020-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgid', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='username')),
                ('menu', models.CharField(blank=True, max_length=100, null=True, verbose_name='menu')),
                ('selected_product', models.IntegerField(blank=True, null=True, verbose_name='product')),
            ],
            options={
                'verbose_name': 'TG User',
                'verbose_name_plural': 'TG Users',
            },
        ),
    ]
