# Generated by Django 3.0.2 on 2020-01-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='company'),
        ),
    ]
